apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: app
          image: localhost:5000/laravel-limewire-docker-app:latest
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: app
            - name: SERVICE_TAGS
              value: dev
          workingDir: /var/www/html
          volumeMounts:
            - mountPath: /var/www/html
              name: app-volume
      volumes:
        - name: app-volume
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  local.ini: |
    # Contents of your local.ini file
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: webserver
          image: nginx:alpine
          volumeMounts:
            - mountPath: /var/www/html
              name: app-volume
            - mountPath: /etc/nginx/conf.d/
              name: nginx-config
      volumes:
        - name: app-volume
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Contents of your default nginx configuration
