name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: shell.r6.websupport.sk
          port: 28114
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd zelopb.sk
            cd web
            git pull origin master
            ls
