name: Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SSH to Server and Download Repository
        run: |
            ssh uid4943252@shell.r6.websupport.sk -p29701 "git clone git@github.com:janzelinka/laravel-limewire-docker.git /zelopb.sk/web"
  
      - name: Install Composer Dependencies
        run: |
            ssh uid4943252@shell.r6.websupport.sk -p29701 "cd /zelopb.sk/web && composer install"
  
      - name: Install npm Dependencies
        run: |
            ssh uid4943252@shell.r6.websupport.sk -p29701 "cd /zelopb.sk/webn && npm install"
