name: Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SSH to Server and Download Repository
        run: |
            ssh uid4943252@shell.r6.websupport.sk -p26391 "git clone https://github.com/yourusername/yourrepository.git /path/to/destination"
  
      - name: Install Composer Dependencies
        run: |
            ssh uid4943252@shell.r6.websupport.sk -p26391 "cd /path/to/destination && composer install"
  
      - name: Install npm Dependencies
        run: |
            ssh uid4943252@shell.r6.websupport.sk -p26391 "cd /path/to/destination && npm install"