name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: shell.r6.websupport.sk
          port: 28114
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd zelopb.sk
            cd web
            git pull origin master
            ls
