name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine changed files
        id: changed_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          echo "::set-output name=files::$(cat changed_files.txt)"

      - name: Upload changed files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: changed-files
          path: changed_files.txt

      - name: FTP Download changed files artifact
        uses: actions/download-artifact@v2
        with:
          name: changed-files
          path: changed_files

      - name: FTP Deploy
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        uses: SamKirkland/FTP-Deploy-Action@v2.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./changed_files
          remote-dir: /zelopb.sk/web

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node dependencies
        run: npm install

      - name: SSH and Install Composer Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /path/to/project
            composer install
